const projects = [
  {
    title: 'Script to Sound',
    description:
      'Developed for the November 2024 Code Institute Hackathon, this project is a text-to-speech application that enhances accessibility by converting written text into spoken words.',
    github: 'https://github.com/hannahro15/Nov24Hackathon',
    demo: 'https://script-to-sound-f697c5a0720c.herokuapp.com/',
    technologies: [
      'Django',
      'HTML5',
      'CSS3',
      'JavaScript',
      'Bootstrap',
      'Python',
      'Agile',
    ],
    collaborative: true,
    isHackathon: false,
    isHackathon_3: true,
    api: false,
  },
  {
    title: 'Portfolio',
    description:
      'A personal portfolio site showcasing my skills, experience, and projects with custom gradient styling.',
    github: 'https://github.com/j0hanz/j0hanz-portfolio',
    demo: 'https://linus-johansson-cv-d308be9b73e1.herokuapp.com/',
    technologies: [
      'React.js',
      'CSS3',
      'JavaScript',
      'Bootstrap',
      'Node.js',
      'EmailJS',
      'Heroku',
    ],
    collaborative: false,
    isHackathon: false,
    isHackathon_3: false,
    api: false,
  },
  {
    title: 'SonataCraft',
    description:
      'A digital Baroque-era piano application allowing users to play and practice sheet music, with information on classical instruments.',
    github: 'https://github.com/Damitwhy/Team4-Sep2024-Hackathon',
    demo: 'https://team4-91bfea18c336.herokuapp.com/',
    technologies: [
      'HTML5',
      'CSS3',
      'JavaScript',
      'Bootstrap',
      'Git',
      'Python',
      'Heroku',
      'SQL',
      'Django',
      'Agile',
    ],
    collaborative: true,
    isHackathon: true,
    isHackathon_3: false,
    api: false,
  },
  {
    title: 'Blog Beat',
    description: 'A platform for reading and writing blog posts.',
    github: 'https://github.com/j0hanz/blog-beat-web',
    demo: 'https://blog-beat-17c62545ca2a.herokuapp.com/',
    technologies: [
      'React.js',
      'CSS3',
      'JavaScript',
      'Bootstrap',
      'Node.js',
      'Agile',
    ],
    collaborative: false,
    isHackathon: false,
    isHackathon_3: false,
    api: false,
  },
  {
    title: 'Blog Beat API',
    description:
      'RESTful API for Blog Beat with endpoints for posts, comments, and authentication.',
    github: 'https://github.com/j0hanz/blog_beat_api',
    demo: 'https://blog-beat-api-bab609deb9ee.herokuapp.com/',
    technologies: ['Django', 'Django REST Framework', 'Python', 'PostgreSQL'],
    collaborative: false,
    isHackathon: false,
    api: true,
  },
  {
    title: 'Tech Corner',
    description:
      'A community blog and news site for tech enthusiasts to share and engage with the latest in technology.',
    github: 'https://github.com/j0hanz/tech-corner-website',
    demo: 'https://tech-corner-web-70b84e69e118.herokuapp.com/about/',
    technologies: [
      'HTML5',
      'CSS3',
      'Python',
      'JavaScript',
      'Bootstrap',
      'Python',
      'Django',
      'SQL',
      'Agile',
    ],
    collaborative: false,
    isHackathon: false,
    isHackathon_3: false,
    api: false,
  },
  {
    title: 'Pick my Spell',
    description:
      'A fun spelling quiz game where users pick the correct word within 10 seconds, perfect for improving spelling skills.',
    github: 'https://github.com/j0hanz/PICK-my-SPELL',
    demo: 'https://j0hanz.github.io/PICK-my-SPELL/',
    technologies: ['HTML5', 'CSS3', 'JavaScript'],
    isHackathon: false,
    isHackathon_3: false,
    collaborative: false,
    api: false,
  },
  {
    title: 'Fix my Spell',
    description:
      'A console-based game to correct misspelled words, designed to boost spelling and vocabulary in a playful way.',
    github: 'https://github.com/j0hanz/FIX-my-SPELL',
    demo: 'https://fix-my-spell-7e3aef96045e.herokuapp.com/',
    technologies: ['Python', 'Heruko'],
    collaborative: false,
    isHackathon: false,
    isHackathon_3: false,
    api: false,
  },
  {
    title: 'Corner',
    description:
      'Corner is an upgraded version of Blog Beat, offering more features, better customization, and an improved user experience.',
    github: 'https://github.com/j0hanz/corner',
    demo: '', // No demo link available
    technologies: [
      'React.js',
      'CSS3',
      'JavaScript',
      'Bootstrap',
      'Node.js',
      'Django Rest',
      'Python',
      'SQL',
      'SEO',
    ],
    collaborative: false,
    isHackathon: false,
    isHackathon_3: false,
    api: false,
  },
];

export default projects;
